name: Test

env:
  NAME: public
on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    needs: Train
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Pull Docker image
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}" | docker pull ssgaur94/ssgaur94_iisc_img:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run Docker container
      run: docker run ssgaur94/ssgaur94_iisc_img:latest
